apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hola-ing
spec:
  rules:
  - host: config.HOLA_DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: hola-svc
          servicePort: 80
